import type { ActivityRecord, ArchivedTaskRecord, TimeLogRecord, TimeReportPreset, TodoRecord } from "@notesmith/domain";
import type { StructureOptions } from "../../../lib/structure/options";
type TimeWorkspaceProps = {
    todos: TodoRecord[];
    archivedTasks: ArchivedTaskRecord[];
    activities: ActivityRecord[];
    timeLogs: TimeLogRecord[];
    structureOptions: StructureOptions;
    requestedDomain?: string | null;
    requestedProject?: string | null;
    reportPresets: TimeReportPreset[];
    baselineWorkActivityId: string;
    isBaselineWorkEnabled: boolean;
    isBaselineWorkRunning: boolean;
    hasSpecificRunningTimeLog: boolean;
    onSaveTimeLog: (timeLog: TimeLogRecord) => void;
    onDeleteTimeLog: (id: string) => void;
    onStartTracking: (targetType: "todo" | "activity", targetId: string) => void;
    onStopTracking: (targetType: "todo" | "activity", targetId: string) => void;
    onStartWorkBaseline: () => void;
    onStopWorkBaseline: () => void;
    onStartAdhocTimeLog: (options?: {
        domain?: string;
        project?: string;
        activity?: string;
    }) => void;
    onOpenTodoDetail: (todoId: string) => void;
    onOpenActivityDetail: (activityId: string) => void;
    onSaveTodo: (todo: TodoRecord) => void;
    onSaveActivity: (activity: ActivityRecord) => void;
    onSaveReportPreset: (preset: Omit<TimeReportPreset, "id">) => void;
    onDeleteReportPreset: (presetId: string) => void;
};
type DatePreset = "today" | "this-week" | "this-month" | "custom";
export declare const formatMinutes: (minutes: number) => string;
export declare const formatDateInput: (date: Date) => string;
export declare const shiftDays: (value: string, days: number) => string;
export declare const differenceInDaysInclusive: (fromDate: string, toDate: string) => number;
export declare const getPresetRange: (preset: Exclude<DatePreset, "custom">, now?: Date) => {
    fromDate: string;
    toDate: string;
    label: string;
};
export declare const calculateDurationMinutes: (date: string, startTime: string, endTime: string) => number;
export declare const buildExportFilename: (kind: "csv" | "md", now?: Date) => string;
export declare const buildJsonExportFilename: (now?: Date) => string;
export declare const TimeWorkspace: ({ todos, archivedTasks, activities, timeLogs, structureOptions, requestedDomain, requestedProject, reportPresets, baselineWorkActivityId, isBaselineWorkEnabled, isBaselineWorkRunning, hasSpecificRunningTimeLog, onSaveTimeLog, onDeleteTimeLog, onStartTracking, onStopTracking, onStartWorkBaseline, onStopWorkBaseline, onStartAdhocTimeLog, onOpenTodoDetail, onOpenActivityDetail, onSaveTodo, onSaveActivity, onSaveReportPreset, onDeleteReportPreset, }: TimeWorkspaceProps) => import("react/jsx-runtime").JSX.Element;
export {};
