import { type ReactNode } from "react";
import type { SessionRecord, TodoRecord } from "@notesmith/domain";
import { type StructureOptions } from "../../../lib/structure/options";
export declare const preserveNotebookRowBreaks: (value: string) => string;
export declare const getNotebookTitleText: (session: Pick<SessionRecord, "date" | "title">) => string;
export declare const buildNotebookSessionTitle: (date: string, titleText: string) => string;
export declare const getNotebookListTitle: (session: Pick<SessionRecord, "captureMode" | "date" | "title">) => string;
interface NotebookWorkspaceProps {
    sessions: SessionRecord[];
    todos: TodoRecord[];
    runningTodoIds: string[];
    activeSession: SessionRecord;
    structureOptions: StructureOptions;
    isTimeTracking: boolean;
    isRecordingAudio: boolean;
    isTranscribingAudio: boolean;
    isGenerating: boolean;
    recordingStatusNote?: string | null;
    outputContent: ReactNode;
    onSelect: (sessionId: string) => void;
    onCreate: () => void;
    onDelete: (sessionId: string) => void;
    onAddTodo: (description: string) => void;
    onSaveTodo: (todo: TodoRecord) => void;
    onDeleteTodo: (todoId: string) => void;
    onAddNoteForTodo: (todoId: string) => void;
    onToggleTodoTime: (todoId: string, isRunning: boolean) => void;
    onChange: (session: SessionRecord) => void;
    onToggleRecording: () => void;
    onUploadAudio: () => void;
    onTranscribeAudio: () => void;
    onGenerateOutput: () => void;
    onOpenInNotes: (view: "capture" | "output") => void;
    onToggleTimeTracking: () => void;
}
export declare const NotebookWorkspace: ({ sessions, todos, runningTodoIds, activeSession, structureOptions, isTimeTracking, isRecordingAudio, isTranscribingAudio, isGenerating, recordingStatusNote, outputContent, onSelect, onCreate, onDelete, onAddTodo, onSaveTodo, onDeleteTodo, onAddNoteForTodo, onToggleTodoTime, onChange, onToggleRecording, onUploadAudio, onTranscribeAudio, onGenerateOutput, onOpenInNotes, onToggleTimeTracking, }: NotebookWorkspaceProps) => import("react/jsx-runtime").JSX.Element;
export {};
