import type { CaptureMode, ChecklistRecord, ChecklistRecurrenceCadence, ChecklistTemplateRecord, DesktopAppSnapshot, TimeLogRecord } from "@notesmith/domain";
import { createAppRepository } from "../lib/db/repository";
type DesktopView = "capture" | "output";
type SaveState = "saved" | "saving" | "error";
type Snapshot = DesktopAppSnapshot;
type TimeLog = TimeLogRecord;
export declare const findNearestAvailableTodoSlot: (calendarItems: Snapshot["calendarItems"], date: string, preferredSlot?: number) => number;
export declare const rollForwardOverdueCalendarTodos: (snapshot: Snapshot, today?: string) => {
    snapshot: DesktopAppSnapshot;
    changed: boolean;
};
interface DesktopState {
    snapshot: DesktopAppSnapshot | null;
    activeSessionId: string | null;
    activeView: DesktopView;
    saveState: SaveState;
    lastSavedAt: string | null;
    isLoaded: boolean;
    loadError: string | null;
    repository: ReturnType<typeof createAppRepository>;
    load: () => Promise<void>;
    setActiveView: (view: DesktopView) => void;
    setActiveSessionId: (id: string) => void;
    saveSession: (payload: DesktopAppSnapshot["sessions"][number]) => Promise<void>;
    createNewSession: (options?: {
        templateId?: string;
        captureMode?: CaptureMode;
    }) => Promise<void>;
    deleteSession: (id: string) => Promise<void>;
    restoreSession: (id: string) => Promise<void>;
    permanentlyDeleteSession: (id: string) => Promise<void>;
    saveTodo: (todo: DesktopAppSnapshot["todos"][number]) => Promise<void>;
    addTodo: (description: string, options?: {
        activityId?: string;
        domain?: string;
        project?: string;
        activityLabel?: string;
        doOn?: string;
        comments?: string;
    }) => Promise<void>;
    deleteTodo: (id: string) => Promise<void>;
    saveActivity: (activity: DesktopAppSnapshot["activities"][number]) => Promise<void>;
    addActivity: (description: string, type?: DesktopAppSnapshot["activities"][number]["type"], options?: {
        parentActivityId?: string;
        domain?: string;
        project?: string;
        activityLabel?: string;
        doOn?: string;
        startTime?: string;
        endTime?: string;
        comments?: string;
    }) => Promise<void>;
    deleteActivity: (id: string) => Promise<void>;
    saveChecklist: (checklist: ChecklistRecord) => Promise<void>;
    createChecklist: (ownerType: ChecklistRecord["ownerType"], ownerId: string, title: string) => Promise<void>;
    deleteChecklist: (id: string) => Promise<void>;
    saveChecklistTemplate: (template: ChecklistTemplateRecord) => Promise<void>;
    createChecklistTemplate: (title: string, category?: string, items?: ChecklistTemplateRecord["items"]) => Promise<void>;
    deleteChecklistTemplate: (id: string) => Promise<void>;
    createChecklistFromTemplate: (ownerType: ChecklistRecord["ownerType"], ownerId: string, templateId: string) => Promise<void>;
    createChecklistRecurrence: (ownerType: ChecklistRecord["ownerType"], ownerId: string, templateId: string, cadence: ChecklistRecurrenceCadence) => Promise<void>;
    deleteChecklistRecurrence: (id: string) => Promise<void>;
    saveTimeLog: (timeLog: TimeLog) => Promise<void>;
    deleteTimeLog: (id: string) => Promise<void>;
    startTimeTracking: (targetType: TimeLog["targetType"], targetId: string) => Promise<void>;
    stopTimeTracking: (targetType: TimeLog["targetType"], targetId: string) => Promise<void>;
    startWorkBaseline: () => Promise<void>;
    stopWorkBaseline: () => Promise<void>;
    createCalendarEntryFromText: (date: string, startSlot: number, value: string, options?: {
        activityId?: string;
        parentActivityId?: string;
        kind?: "todo" | "meeting";
        endSlot?: number;
    }) => Promise<string | null>;
    rollForwardOverdueTodos: () => Promise<void>;
    moveCalendarItem: (id: string, date: string, startSlot: number) => Promise<void>;
    updateCalendarItem: (id: string, updates: {
        date: string;
        startSlot: number;
        durationSlots: number;
    }) => Promise<void>;
    convertTodoToActivity: (todo: DesktopAppSnapshot["todos"][number], options?: {
        type?: DesktopAppSnapshot["activities"][number]["type"];
        date?: string;
        startTime?: string;
        endTime?: string;
    }) => Promise<string | null>;
    ensureSessionForActivity: (activityId: string) => Promise<string | null>;
    ensureSessionForTodo: (todoId: string) => Promise<string | null>;
    saveSettings: (settings: DesktopAppSnapshot["settings"]) => Promise<void>;
    renameDomainValue: (previousValue: string, nextValue: string) => Promise<void>;
    renameProjectValue: (previousValue: string, nextValue: string) => Promise<void>;
    saveTemplate: (template: DesktopAppSnapshot["templates"][number]) => Promise<void>;
    resetTemplates: () => Promise<void>;
    importLegacyBrowserData: () => Promise<"imported" | "missing">;
    importBackupSnapshot: (snapshot: DesktopAppSnapshot) => Promise<void>;
    saveAttachments: (attachments: DesktopAppSnapshot["attachments"]) => Promise<void>;
}
export declare const useDesktopStore: import("zustand").UseBoundStore<import("zustand").StoreApi<DesktopState>>;
export {};
