export const DEFAULT_OUTPUT_LAYOUT_PRESET_ID = "modern-minutes";
const LEGACY_OUTPUT_LAYOUT_PRESET_MAP = {
    "modern-aptos": "modern-minutes",
    "enterprise-helvetica": "executive-brief",
    "editorial-georgia": "narrative-memo",
    "board-briefing": "formal-board",
    "digital-inter": "decision-log",
    "refined-garamond": "formal-board",
};
export const OUTPUT_LAYOUT_PRESETS = [
    {
        id: "executive-brief",
        label: "Executive brief",
        description: "A polished leadership-ready layout with centered title treatment, disciplined spacing, and calm contrast.",
        bestFor: "Leadership updates, client-ready summaries, and polished executive readouts.",
        style: {
            titleFont: "\"Aptos Display\", Aptos, Calibri, Arial, sans-serif",
            headingFont: "Aptos, Calibri, Arial, sans-serif",
            bodyFont: "Aptos, Calibri, Arial, sans-serif",
            metaFont: "Aptos, Calibri, Arial, sans-serif",
            titleSize: 24,
            headingSize: 13,
            bodySize: 11,
            metaSize: 9.5,
            lineHeight: 1.55,
            pageMargin: 34,
            titleAlign: "center",
            metaAlign: "center",
            headingCase: "sentence",
            headingColor: "#274c77",
            metaColor: "#5f6f85",
            paragraphSpacing: 12,
            sectionSpacing: 24,
            sectionDivider: "line",
        },
        pdfFonts: {
            title: "helvetica",
            heading: "helvetica",
            body: "helvetica",
            meta: "helvetica",
        },
    },
    {
        id: "modern-minutes",
        label: "Modern minutes",
        description: "The new default: crisp sans-serif minutes with efficient page use, sentence-case headings, and balanced spacing.",
        bestFor: "Most business meetings, recurring team notes, and everyday professional documentation.",
        style: {
            titleFont: "\"Aptos Display\", Aptos, Calibri, Arial, sans-serif",
            headingFont: "Aptos, Calibri, Arial, sans-serif",
            bodyFont: "Aptos, Calibri, Arial, sans-serif",
            metaFont: "Aptos, Calibri, Arial, sans-serif",
            titleSize: 22,
            headingSize: 12.5,
            bodySize: 11,
            metaSize: 9.5,
            lineHeight: 1.52,
            pageMargin: 30,
            titleAlign: "left",
            metaAlign: "left",
            headingCase: "sentence",
            headingColor: "#2f5d43",
            metaColor: "#667565",
            paragraphSpacing: 11,
            sectionSpacing: 20,
            sectionDivider: "none",
        },
        pdfFonts: {
            title: "helvetica",
            heading: "helvetica",
            body: "helvetica",
            meta: "helvetica",
        },
    },
    {
        id: "formal-board",
        label: "Formal board",
        description: "A more traditional document voice with serif hierarchy, steadier rhythm, and formal section separation.",
        bestFor: "Board, committee, governance, and official record-style minutes.",
        style: {
            titleFont: "Georgia, Cambria, \"Times New Roman\", serif",
            headingFont: "Georgia, Cambria, \"Times New Roman\", serif",
            bodyFont: "\"Helvetica Neue\", Arial, sans-serif",
            metaFont: "\"Helvetica Neue\", Arial, sans-serif",
            titleSize: 24,
            headingSize: 13.5,
            bodySize: 11,
            metaSize: 9.5,
            lineHeight: 1.62,
            pageMargin: 44,
            titleAlign: "left",
            metaAlign: "left",
            headingCase: "sentence",
            headingColor: "#1d3557",
            metaColor: "#6d6a64",
            paragraphSpacing: 12,
            sectionSpacing: 24,
            sectionDivider: "line",
        },
        pdfFonts: {
            title: "times",
            heading: "times",
            body: "helvetica",
            meta: "helvetica",
        },
    },
    {
        id: "narrative-memo",
        label: "Narrative memo",
        description: "A paragraph-first memo style built for flowing prose, deeper discussion summaries, and less bullet-heavy minutes.",
        bestFor: "Workshops, strategy sessions, 1:1s, and nuanced discussion writeups.",
        style: {
            titleFont: "Georgia, Cambria, \"Times New Roman\", serif",
            headingFont: "Georgia, Cambria, \"Times New Roman\", serif",
            bodyFont: "Georgia, Cambria, \"Times New Roman\", serif",
            metaFont: "\"Helvetica Neue\", Arial, sans-serif",
            titleSize: 23,
            headingSize: 12.5,
            bodySize: 11.5,
            metaSize: 9,
            lineHeight: 1.68,
            pageMargin: 36,
            titleAlign: "left",
            metaAlign: "left",
            headingCase: "sentence",
            headingColor: "#5c4332",
            metaColor: "#7a6b5d",
            paragraphSpacing: 14,
            sectionSpacing: 18,
            sectionDivider: "none",
        },
        pdfFonts: {
            title: "times",
            heading: "times",
            body: "times",
            meta: "helvetica",
        },
    },
    {
        id: "decision-log",
        label: "Decision log",
        description: "An operations-first layout with stronger section contrast and sharper separation of decisions and follow-ups.",
        bestFor: "Steering groups, delivery meetings, risk reviews, and action-heavy notes.",
        style: {
            titleFont: "Inter, Segoe UI, Arial, sans-serif",
            headingFont: "Inter, Segoe UI, Arial, sans-serif",
            bodyFont: "\"Source Sans 3\", Inter, Segoe UI, Arial, sans-serif",
            metaFont: "\"Source Sans 3\", Inter, Segoe UI, Arial, sans-serif",
            titleSize: 21.5,
            headingSize: 12.5,
            bodySize: 10.5,
            metaSize: 9,
            lineHeight: 1.46,
            pageMargin: 28,
            titleAlign: "left",
            metaAlign: "left",
            headingCase: "sentence",
            headingColor: "#8b3d2f",
            metaColor: "#6a6f7f",
            paragraphSpacing: 10,
            sectionSpacing: 22,
            sectionDivider: "line",
        },
        pdfFonts: {
            title: "helvetica",
            heading: "helvetica",
            body: "helvetica",
            meta: "helvetica",
        },
    },
    {
        id: "compact-action-pack",
        label: "Compact action pack",
        description: "A denser, space-efficient layout with tighter margins and tighter rhythm for high-volume internal documentation.",
        bestFor: "Internal working packs, frequent recurring meetings, and maximum information per page.",
        style: {
            titleFont: "Inter, Segoe UI, Arial, sans-serif",
            headingFont: "Inter, Segoe UI, Arial, sans-serif",
            bodyFont: "\"Source Sans 3\", Inter, Segoe UI, Arial, sans-serif",
            metaFont: "\"Source Sans 3\", Inter, Segoe UI, Arial, sans-serif",
            titleSize: 19.5,
            headingSize: 11.5,
            bodySize: 10.25,
            metaSize: 8.5,
            lineHeight: 1.38,
            pageMargin: 24,
            titleAlign: "left",
            metaAlign: "left",
            headingCase: "sentence",
            headingColor: "#314b6b",
            metaColor: "#707987",
            paragraphSpacing: 8,
            sectionSpacing: 16,
            sectionDivider: "line",
        },
        pdfFonts: {
            title: "helvetica",
            heading: "helvetica",
            body: "helvetica",
            meta: "helvetica",
        },
    },
];
export const isOutputLayoutPresetId = (value) => Boolean(value && OUTPUT_LAYOUT_PRESETS.some((preset) => preset.id === value));
export const normalizeOutputLayoutPresetId = (value) => {
    if (!value) {
        return DEFAULT_OUTPUT_LAYOUT_PRESET_ID;
    }
    const normalized = LEGACY_OUTPUT_LAYOUT_PRESET_MAP[value] || value;
    return isOutputLayoutPresetId(normalized) ? normalized : DEFAULT_OUTPUT_LAYOUT_PRESET_ID;
};
export const getOutputLayoutPreset = (presetId) => OUTPUT_LAYOUT_PRESETS.find((preset) => preset.id === normalizeOutputLayoutPresetId(presetId))
    ?? OUTPUT_LAYOUT_PRESETS.find((preset) => preset.id === DEFAULT_OUTPUT_LAYOUT_PRESET_ID)
    ?? OUTPUT_LAYOUT_PRESETS[0];
export const getPrimaryFontFamily = (fontStack) => fontStack
    .split(",")[0]
    ?.trim()
    .replace(/^["']|["']$/g, "")
    || "Aptos";
