import { type StructureOptions } from "../../../lib/structure/options";
import type { RecordingMode } from "../../../lib/files/recording";
import { type AttachmentRecord, type CaptureMode, type CaptureWorkspaceDensity, type SessionRecord, type TemplateDefinition } from "@notesmith/domain";
interface GenerationLogEntry {
    id: string;
    timestamp: string;
    level: "info" | "success" | "warning" | "error";
    message: string;
    details?: string;
}
interface SessionEditorProps {
    session: SessionRecord;
    templates: TemplateDefinition[];
    allowedTemplateCaptureModes?: CaptureMode[];
    attachments: AttachmentRecord[];
    presentation?: CaptureWorkspaceDensity;
    showPresentationActions?: boolean;
    showPanelHeading?: boolean;
    showQuickStartTemplates?: boolean;
    savedPeople: string[];
    suggestedPeople: string[];
    savedProjects: string[];
    suggestedProjects: string[];
    savedDomains: string[];
    suggestedDomains: string[];
    savedActivities: string[];
    suggestedActivities: string[];
    structureOptions: StructureOptions;
    savedTags: string[];
    suggestedTags: string[];
    isTranscribingAudio: boolean;
    recordingMode: RecordingMode;
    isRecordingAudio: boolean;
    recordingStatusNote?: string | null;
    generationLog?: GenerationLogEntry[];
    onClearGenerationLog?: () => void;
    onChange: (session: SessionRecord) => void;
    onImportTranscript: () => void;
    onImportAudio: () => void;
    onImportImage: () => void;
    onCreateInlineImageAttachment?: (file: File) => Promise<AttachmentRecord | null>;
    onTranscribeAudio: () => void;
    onChangeRecordingMode: (mode: RecordingMode) => void;
    onStartRecording: (mode?: RecordingMode) => void;
    onStopRecording: () => void;
    onRemoveAttachment: (attachmentId: string) => void;
    onUpdateAttachment: (attachment: AttachmentRecord) => void;
    onOpenDetails?: () => void;
    onCreateSessionFromTemplate?: (templateId: string) => void;
    onOpenInstructions?: () => void;
}
export declare const getSessionEditorTemplateOptions: (templates: TemplateDefinition[], captureMode: CaptureMode, allowedCaptureModes?: CaptureMode[]) => TemplateDefinition[];
export declare const SessionEditor: ({ session, templates, allowedTemplateCaptureModes, attachments, presentation, showPresentationActions, showPanelHeading, showQuickStartTemplates, savedPeople, suggestedPeople, savedProjects, suggestedProjects, savedDomains, suggestedDomains, savedActivities, suggestedActivities, structureOptions, savedTags, suggestedTags, isTranscribingAudio, recordingMode, isRecordingAudio, recordingStatusNote, generationLog, onClearGenerationLog, onChange, onImportTranscript, onImportAudio, onImportImage, onCreateInlineImageAttachment, onTranscribeAudio, onChangeRecordingMode, onStartRecording, onStopRecording, onRemoveAttachment, onUpdateAttachment, onOpenDetails, onCreateSessionFromTemplate, onOpenInstructions, }: SessionEditorProps) => import("react/jsx-runtime").JSX.Element;
export {};
