import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const DETAIL_LEVEL_LABELS = {
    1: "Minimal",
    2: "Concise",
    3: "Balanced",
    4: "Detailed",
    5: "Comprehensive",
};
export const SessionEditor = ({ session, templates, attachments, isTranscribingAudio, onChange, onImportTranscript, onImportAudio, onTranscribeAudio, onRemoveAttachment, }) => {
    const update = (key, value) => onChange({ ...session, [key]: value });
    const activeTemplate = templates.find((template) => template.id === session.templateId) ?? templates[0];
    const customFields = activeTemplate?.fields.filter((field) => field.enabled &&
        !["title", "participants", "date", "startTime", "endTime"].includes(field.key)) ?? [];
    const enabledSections = activeTemplate?.sections.map((section) => ({
        ...section,
        checked: !session.excludedSectionIds.includes(section.id),
    })) ?? [];
    return (_jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsxs("div", { children: [_jsx("h2", { children: "Capture" }), _jsx("p", { children: "Sessions stay local-first, but this UI is already shaped for the future Tauri + SQLite architecture." })] }) }), _jsxs("div", { className: "form-grid", children: [_jsxs("div", { className: "field field-wide", children: [_jsx("label", { htmlFor: "template-select", children: "Template" }), _jsx("select", { id: "template-select", value: session.templateId, onChange: (event) => {
                                    const nextTemplate = templates.find((template) => template.id === event.target.value);
                                    const nextFieldValues = Object.fromEntries((nextTemplate?.fields ?? [])
                                        .filter((field) => field.enabled &&
                                        !["title", "participants", "date", "startTime", "endTime"].includes(field.key))
                                        .map((field) => [field.id, session.customFieldValues[field.id] ?? ""]));
                                    onChange({
                                        ...session,
                                        templateId: event.target.value,
                                        customFieldValues: nextFieldValues,
                                        excludedSectionIds: [],
                                    });
                                }, children: templates.map((template) => (_jsx("option", { value: template.id, children: template.name }, template.id))) })] }), _jsxs("div", { className: "field field-wide", children: [_jsx("label", { htmlFor: "session-title", children: "Title" }), _jsx("input", { id: "session-title", value: session.title, onChange: (event) => update("title", event.target.value), placeholder: "Weekly project meeting" })] }), _jsxs("div", { className: "field", children: [_jsx("label", { htmlFor: "session-date", children: "Date" }), _jsx("input", { id: "session-date", type: "date", value: session.date, onChange: (event) => update("date", event.target.value) })] }), _jsxs("div", { className: "field", children: [_jsx("label", { htmlFor: "session-participants", children: "Participants" }), _jsx("input", { id: "session-participants", value: session.participantText, onChange: (event) => update("participantText", event.target.value), placeholder: "Add participants" })] }), _jsxs("div", { className: "field", children: [_jsx("label", { htmlFor: "session-start", children: "Start time" }), _jsx("input", { id: "session-start", type: "time", value: session.startTime, onChange: (event) => update("startTime", event.target.value) })] }), _jsxs("div", { className: "field", children: [_jsx("label", { htmlFor: "session-end", children: "End time" }), _jsx("input", { id: "session-end", type: "time", value: session.endTime, onChange: (event) => update("endTime", event.target.value) })] }), _jsxs("div", { className: "field field-wide", children: [_jsx("label", { htmlFor: "manual-notes", children: "Manual notes" }), _jsx("textarea", { id: "manual-notes", value: session.manualNotes, onChange: (event) => update("manualNotes", event.target.value), placeholder: "Capture the rough notes here. This is where later AI services will read from." })] }), _jsxs("div", { className: "field field-wide", children: [_jsx("label", { htmlFor: "quick-highlights", children: "Quick highlights" }), _jsx("textarea", { id: "quick-highlights", value: session.quickHighlights, onChange: (event) => update("quickHighlights", event.target.value), placeholder: "Short key points, names, or topics to emphasize in the final output." })] }), customFields.map((field) => (_jsxs("div", { className: field.type === "textarea" ? "field field-wide" : "field", children: [_jsx("label", { htmlFor: `custom-field-${field.id}`, children: field.label }), field.type === "textarea" ? (_jsx("textarea", { id: `custom-field-${field.id}`, value: session.customFieldValues[field.id] ?? "", onChange: (event) => update("customFieldValues", {
                                    ...session.customFieldValues,
                                    [field.id]: event.target.value,
                                }) })) : (_jsx("input", { id: `custom-field-${field.id}`, type: field.type === "number" ? "number" : field.type, value: session.customFieldValues[field.id] ?? "", onChange: (event) => update("customFieldValues", {
                                    ...session.customFieldValues,
                                    [field.id]: event.target.value,
                                }) }))] }, field.id))), _jsxs("div", { className: "field", children: [_jsx("label", { htmlFor: "detail-level", children: "Detail level" }), _jsx("select", { id: "detail-level", value: String(session.detailLevel), onChange: (event) => update("detailLevel", Number(event.target.value)), children: Object.entries(DETAIL_LEVEL_LABELS).map(([value, label]) => (_jsxs("option", { value: value, children: [value, " - ", label] }, value))) })] }), _jsxs("div", { className: "field field-wide", children: [_jsx("label", { htmlFor: "live-transcript", children: "Live transcript" }), _jsx("textarea", { id: "live-transcript", value: session.liveTranscript, onChange: (event) => update("liveTranscript", event.target.value), placeholder: "Recorded transcript text will land here." })] }), enabledSections.length ? (_jsxs("div", { className: "field field-wide", children: [_jsx("label", { children: "Output sections for this session" }), _jsx("div", { className: "section-list", children: enabledSections.map((section) => (_jsxs("label", { className: "list-item checkbox-label", children: [_jsx("input", { type: "checkbox", checked: section.checked, onChange: (event) => update("excludedSectionIds", event.target.checked
                                                ? session.excludedSectionIds.filter((id) => id !== section.id)
                                                : Array.from(new Set([...session.excludedSectionIds, section.id]))) }), _jsxs("span", { children: [_jsx("strong", { children: section.title }), _jsx("span", { className: "muted", children: section.instructions })] })] }, section.id))) })] })) : null, _jsxs("div", { className: "page-actions field-wide", children: [_jsx("button", { className: "small-button", type: "button", onClick: onImportAudio, children: "Upload audio" }), _jsx("button", { className: "small-button", type: "button", onClick: onTranscribeAudio, children: isTranscribingAudio ? "Transcribing audio..." : "Transcribe audio" }), _jsx("button", { className: "small-button", type: "button", onClick: onImportTranscript, children: "Upload transcript file" })] }), attachments.length ? (_jsxs("div", { className: "field field-wide", children: [_jsx("label", { children: "Session attachments" }), _jsx("div", { className: "section-list", children: attachments.map((attachment) => (_jsxs("div", { className: "list-item", children: [_jsx("strong", { children: attachment.filename }), _jsxs("span", { className: "muted", children: [attachment.kind, " \u00B7 ", Math.max(1, Math.round(attachment.sizeBytes / 1024)), " KB"] }), _jsx("div", { className: "list-item-actions", children: _jsx("button", { className: "small-button danger-button", type: "button", onClick: () => onRemoveAttachment(attachment.id), children: "Remove" }) })] }, attachment.id))) })] })) : null] })] }));
};
