import type { LocalAppSettings, TemplateDefinition } from "@notesmith/domain";
import type { DesktopStorageInfo, LocalBackupInfo } from "../../../lib/storage/desktopStorage";
import type { AIRequestHistoryEntry } from "../../../lib/ai/history";
import type { AIDiagnosticsItem } from "../../../lib/ai/metrics";
import type { SelectModelOption } from "../../../lib/ai/modelPricing";
export type SettingsSection = "ai" | "diagnostics" | "themes" | "output" | "people" | "prompts" | "templates" | "other";
interface SettingsCardProps {
    settings: LocalAppSettings;
    templates: TemplateDefinition[];
    initialSection?: SettingsSection;
    onChange: (settings: LocalAppSettings) => void;
    onSaveTemplate: (template: TemplateDefinition) => void;
    onResetTemplates: () => Promise<void>;
    onImportLegacy: () => Promise<void>;
    onImportBackup: () => Promise<void>;
    onCheckForUpdates: () => Promise<void>;
    onInstallUpdate?: () => Promise<void>;
    onOpenManualUpdate?: () => Promise<void>;
    onOpenDataFolder: () => Promise<void>;
    onOpenDatabaseFolder: () => Promise<void>;
    onExportBackup: () => Promise<void>;
    onSaveBackupAs: () => Promise<void>;
    onRefreshModelPricing: () => Promise<void> | void;
    updateStatusNote?: string | null;
    desktopVersion?: string | null;
    desktopBundleType?: string | null;
    availableUpdateVersion?: string | null;
    manualUpdateUrl?: string | null;
    isCheckingForUpdates?: boolean;
    isInstallingUpdate?: boolean;
    storageInfo: DesktopStorageInfo | null;
    latestLocalBackupInfo: LocalBackupInfo | null;
    aiDiagnostics: AIDiagnosticsItem[];
    aiRequestHistory: AIRequestHistoryEntry[];
    textModelOptions: SelectModelOption[];
    transcriptionModelOptions: SelectModelOption[];
    modelPricingStatus: string;
    isRefreshingModelPricing: boolean;
}
export declare const SettingsCard: ({ settings, templates, initialSection, onChange, onSaveTemplate, onResetTemplates, onImportLegacy, onImportBackup, onCheckForUpdates, onInstallUpdate, onOpenManualUpdate, onOpenDataFolder, onOpenDatabaseFolder, onExportBackup, onSaveBackupAs, onRefreshModelPricing, updateStatusNote, desktopVersion, desktopBundleType, availableUpdateVersion, manualUpdateUrl, isCheckingForUpdates, isInstallingUpdate, storageInfo, latestLocalBackupInfo, aiDiagnostics, aiRequestHistory, textModelOptions, transcriptionModelOptions, modelPricingStatus, isRefreshingModelPricing, }: SettingsCardProps) => import("react/jsx-runtime").JSX.Element;
export {};
